---
version: "2.1"
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${LOCAL_TIME_ZONE}
    volumes:
      - ${LOCAL_LOCATION}:/config
    ports:
      - 8080:80
      - 8443:443
    restart: unless-stopped
