services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - ${PORT}:8080
    volumes:
      - ${LOCAL_LOCATION}:/configs
    environment:
      APP_LOCALE: ${APP_LOCALE}
