version: "3"

services:
  filebrowser:
    image: hurlenko/filebrowser
    ports:
      - ${PORT}:8080
    volumes:
      - ${DATA_DIR}:/data
      - ${CONFIG_DIR}:/config
    restart: unless-stopped
