services:
  redlib:
    image: quay.io/redlib/redlib:latest
    restart: unless-stopped
    ports:
      - 12694:8080 # Specify `127.0.0.1:8080:8080` instead if using a reverse proxy
    read_only: true
    security_opt:
      - no-new-privileges:true
      # - seccomp=seccomp-redlib.json
    cap_drop:
      - ALL
    env_file: .env
    healthcheck:
      test:
        - CMD
        - wget
        - --spider
        - -q
        - --tries=1
        - http://localhost:8080/settings
      interval: 5m
      timeout: 3s
