services:
  task-md:
    image: baldissaramatheus/tasks.md
    container_name: task-md
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    ports:
      - 8100:8080
    volumes:
      - ${LOCAL_LOCATION}/tasks:/tasks/
      - ${LOCAL_LOCATION}/config:/config/
    restart: unless-stopped
