---
version: "3.8"
services:
  grocy:
    image: lscr.io/linuxserver/grocy:4.0.0
    container_name: grocy
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${LOCAL_TIME_ZONE}
    volumes:
      - ${LOCAL_LOCATION}:/config
    ports:
      - 9283:80
      - 9284:443
    restart: unless-stopped
