version: '3.5'
services:
  huginn:
    image: ghcr.io/huginn/huginn
    restart: unless-stopped
    ports:
      - ${PORT}:3000
    volumes:
      - ${LOCAL_LOCATION}:/var/lib/mysql
    environment:
      - SCHEDULER_FREQUENCY=0.5
      - TIMEZONE=${LOCAL_TIMEZONE:-Brisbane}
