---
version: "2.1"
services:
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    environment:
      # - PUID=1000
      # - PGID=1000
      - TZ=${LOCAL_TIME_ZONE}
    volumes:
      - ${LOCAL_LOCATION}:/config
    ports:
      - 8082:80
    restart: unless-stopped
