services:
  snippet-box:
    image: pawelmalak/snippet-box:latest
    container_name: snippet-box
    volumes:
      - ${LOCAL_LOCATION}:/app/data
    ports:
      - ${PORT}:5000
    restart: unless-stopped
